name: textstatsci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev

      - name: Check code spelling
        run: |
          pipenv run codespell -L paket --skip=./textstatsci/resources/**/easy_words.txt,./build/*,./textstatsci.egg-info/*,./.git/* --exclude-file=.codespellignorelines

      - name: Test with pytest
        run: |
          pipenv run pytest test.py

      - name: Test installing package
        run: |
          pip install .